### ISSUE TITLE
rust-1.46.0 fails to compile with error: could not compile `globset` (signal: 4, SIGILL: illegal instruction)

### ISSUE THREAD

**Issue by stefson** [smaeul/portage-overlay#29]
hey there, recently I was forced to upgrade my toolchain from llvm-9 to llvm-10, and thus decided to ramp up my version of dev-lang/rust. I'm on armv7a-unknown-linux-gnueabihf, so I decided to settle for the bit older rust-1.46.0 and save up at least 24hrs of compile time by going USE="+system-llvm" ; however there is a compile error just a few minutes into the compilation: 

```
   Compiling globset v0.4.3
     Running `/var/tmp/portage/dev-lang/rust-1.46.0/work/rust-stage0/bin/rustc --crate-name globset /var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/vendor/globset-0.4.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 -C metadata=ab76e98b9334e597 -C extra-filename=-ab76e98b9334e597 --out-dir /var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps -L dependency=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps --extern aho_corasick=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/libaho_corasick-d92a2f881e500ac2.rmeta --extern bstr=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/libbstr-7165a6e3b3784537.rmeta --extern fnv=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/libfnv-2b3a02f5f5cccc47.rmeta --extern log=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/liblog-c85607dcbdc54081.rmeta --extern regex=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/libregex-da205cfd634c7bba.rmeta --cap-lints allow -Lnative=/usr/lib/llvm/10/lib -Cdebuginfo=2 -C target-feature=-crt-static -C linker=armv7a-unknown-linux-musleabihf-gcc -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings`
error: could not compile `globset`.

Caused by:
  process didn't exit successfully: `/var/tmp/portage/dev-lang/rust-1.46.0/work/rust-stage0/bin/rustc --crate-name globset /var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/vendor/globset-0.4.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 -C metadata=ab76e98b9334e597 -C extra-filename=-ab76e98b9334e597 --out-dir /var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps -L dependency=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps --extern aho_corasick=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/libaho_corasick-d92a2f881e500ac2.rmeta --extern bstr=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/libbstr-7165a6e3b3784537.rmeta --extern fnv=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/libfnv-2b3a02f5f5cccc47.rmeta --extern log=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/liblog-c85607dcbdc54081.rmeta --extern regex=/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/build/bootstrap/debug/deps/libregex-da205cfd634c7bba.rmeta --cap-lints allow -Lnative=/usr/lib/llvm/10/lib -Cdebuginfo=2 -C target-feature=-crt-static -C linker=armv7a-unknown-linux-musleabihf-gcc -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
error: build failed
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/src/bootstrap/bootstrap.py", line 981, in main
    bootstrap(help_triggered)
  File "/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/src/bootstrap/bootstrap.py", line 948, in bootstrap
    build.build_bootstrap()
  File "/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/src/bootstrap/bootstrap.py", line 733, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/var/tmp/portage/dev-lang/rust-1.46.0/work/rustc-1.46.0-src/src/bootstrap/bootstrap.py", line 143, in run
    raise RuntimeError(err)
```

full build log: [failed-rust-1.46.0.log.gz](https://github.com/smaeul/portage-overlay/files/6178051/failed-rust-1.46.0.log.gz)

I'm aware that you have updated the rust ebuild to llvm-11 based 1.47.0, but since it's greatly demanding for the small rpi to mangle down all these big packages, maybe you can have a look into it? Usually, I'm always lagging behind one stable release with compilers, just because the device is so slow.

**Comment by stefson** [comment]
my emerge --info [emerge--info.gz](https://github.com/smaeul/portage-overlay/files/6180016/emerge--info.gz)

**Comment by stefson** [comment]
so it turns out firefox-87.0 demands insane amounts of ram, so much in fact that it seems to overstretch what arm32 is ever able to comprehend. confirmed via cross compile and a host with 32gb of ram. however, it was my intention to use this with armv7a, and given all the gnarly problems with the abi it seems reasonable to switch to aarch64. 

for everyone else: rust-1.47.0-r1 is good friends with musl-1.2.2-r2; at least it doesn't suffer the same bug.
